In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("Iris.csv")
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
dataset.isnull().any()

Id               False
SepalLengthCm    False
SepalWidthCm     False
PetalLengthCm    False
PetalWidthCm     False
Species          False
dtype: bool

# in this dataset "column 0 i.e., ID is not important so we can ignore that particular column as it wont have significant effect on prediction"

In [4]:
x=dataset.iloc[0:, 1:5]
y=dataset.iloc[0:, 5:]
x=x.values
y=y.values

# column y "Target" is in categorical features so before we proceed to model, first we have to preprocess or convert it into integer using LabelEncoder.

In [5]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
y=label.fit_transform(y)

/srv/conda/envs/notebook/lib/python3.6/site-packages/sklearn/preprocessing/_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8)

In [8]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=10, criterion='entropy', random_state=0)
model=rf.fit(x_train,y_train)
prediction=model.predict(x_train)
prediction

array([0, 1, 0, 1, 0, 1, 0, 2, 0, 2, 1, 1, 0, 1, 1, 1, 1, 2, 2, 1, 2, 1,
       2, 0, 1, 0, 1, 1, 0, 0, 2, 2, 2, 1, 2, 2, 2, 1, 1, 2, 2, 2, 0, 0,
       0, 2, 2, 2, 0, 1, 1, 2, 0, 0, 1, 0, 2, 2, 1, 2, 2, 1, 1, 1, 0, 1,
       1, 1, 2, 2, 0, 1, 2, 1, 2, 1, 0, 2, 2, 1, 0, 0, 1, 0, 2, 2, 0, 2,
       2, 1, 1, 0, 0, 0, 2, 0, 2, 2, 1, 1, 1, 2, 1, 0, 0, 1, 1, 0, 1, 0,
       2, 1, 0, 2, 1, 0, 2, 2, 0, 1])

In [9]:
rscore=model.score(x_train,y_train)
rscore

1.0

In [10]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_train, prediction)
cm

array([[35,  0,  0],
       [ 0, 44,  0],
       [ 0,  0, 41]])

# here the rscore or accuracy is 1.0, that shows our model works great and the predictions are also good.